#!/bin/sh -eu
export x "$@"

: ${port:=25} ${timeout:=1} ${host:=$(hostname)} ${mail:=root@$(hostname)}

out() {
	echo "C: $*" >&2
	printf '%s\r\n' "$*"
	sleep 0.4
}

({
	out "EHLO $(hostname)"
	out "MAIL from:<monitoring@$(hostname)>"
	out "RCPT to:<$mail>"
	out "DATA"
	out ""
	out "From: $(whoami)@$host"
	out "To: $mail"
	out "Subject: check=mail time=$(date +%s)"
	out "Date: $(date +'%a, %m %b %Y %H:%M:%S %+z')"
	out "Message-Id: $RANDOM.$RANDOM.$RANDOM.$RANDOM@$host"
	out "X-Monitower: $*"
	out ""
	out "."
} | nc -w "$timeout" "$ip" "$port" | while read code line; do
	echo "S: $code $line" | tr -d '\r'>&2
	case $code in (5*) exit 1 ;; esac
done) 2>&1 | awk '/^S: / { S++; X += ($2 >= 400) } 1 END { exit(!S || X) }'
