#!/bin/sh -eu
#
# Read a single key=value file as input, run the $cmd and store the result as
# "$MONITOWER_SPOOL/$host/$name.log"
#
# This way, no complex configuration or parsing needed every run, and this
# script is inexpensive enough to be run from a /etc/crontab.
#

check() { set -ue
	local "$@"

	mkdir -p "$MONITOWER_SPOOL/$host"

	if "$cmd" "$@" >/dev/null 2>&1; then
		echo time="$(date +%s)" state=ok "$@"
	else
		echo time="$(date +%s)" state=err "$@"
		logger -cs -p "$MONITOWER_FACILITY.${level:-alert}" -t monitower "$@"
	fi >>$MONITOWER_SPOOL/$host/$name.log
}

: ${MONITOWER_SPOOL:=/var/spool/monitower}
: ${MONITOWER_FACILITY:=local7}

while read line; do
	check $line &
done <${1:-/etc/monitower.conf}
wait
