#!/bin/sh -eu
#
# Read a single key=value file as input, run the $cmd and store the result as
# "$MONITOWER_SPOOL/$host/$name.log"
#
# This way, no complex configuration or parsing needed every run, and this
# script is inexpensive enough to be run from a /etc/crontab.
#

check() { set -u +e
	local state level "$@"

	mkdir -p "$MONITOWER_SPOOL/$host"

	"$cmd" "$@" >/dev/null 2>&1

	case $? in
	(0) state=ok level=debug ;;
	(*) state=err ;;
	esac

	logger -cs -t monitower -p "$MONITOWER_FACILITY.${level:-alert}" \
	  time="$NOW" state="$state" "$@"

	echo "time=$NOW state=$state $*" >>$MONITOWER_SPOOL/$host/$name.log
}

: ${MONITOWER_SPOOL:=/var/spool/monitower}
: ${MONITOWER_FACILITY:=local7}

NOW=$(date +%s)
IFS='
'
while read line; do
	check $(echo $line | xargs -n 1) &
done <${1:-/etc/monitower.conf}
wait
