#!/bin/sh -eu
#
# Read a single key=value file as input, run the $cmd and store the result as
# "$MONITOWER_SPOOL/$host/$name.log"
#
# This way, no complex configuration or parsing needed every run, and this
# script is inexpensive enough to be run from a /etc/crontab.
#

check() { set -u +e
	local state level "$@"

	mkdir -p "$MONITOWER_SPOOL/$host"

	"$cmd" "$@" >&2

	case $? in
	(0) state=ok level=debug ;;
	(*) state=err ;;
	esac

	logger -cs -t monitower -p "$MONITOWER_FACILITY.${level:-alert}" \
	  time="$now" state="$state" "$@"

	echo "time=$now state=$state" >>$MONITOWER_SPOOL/$host/$name.log
}

: ${MONITOWER_SPOOL:=/var/spool/monitower}
: ${MONITOWER_FACILITY:=local7}

now=$(date +%s)
IFS='
'
[ $# = 0 ] && set /etc/monitower.conf
sed -r 's,\\\\,\\s,g; s,\\",\\q,g' "$@" | while read line; do
	check $(echo $line | xargs -n 1) &
done
wait
